using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace SqlArtisan.TableClassGen;

// Reads back the files earlier runs wrote, including earlier versions': the table
// literal of every version, the column literal of 0.6 on, the header of 0.8 on, and
// both core-name spellings (FixtureCorpusTests pins the 0.8 and 1.0 shapes).
internal static class CommittedFile
{
    public const string Header = "// <auto-generated/>";

    // Matches the escaped literal TableClassEmitter.Quote produces, so a column
    // name carrying a quote or backslash still round-trips through the diff.
    // 0.8 through 0.12 wrote the core names unqualified, under `using SqlArtisan;`.
    private static readonly Regex ColumnPattern = new(
        """new (?:global::SqlArtisan\.)?DbColumn\(this, "(?<name>(?:[^"\\]|\\.)*)"\)""",
        RegexOptions.Compiled);

    private static readonly Regex TablePattern =
        new(""": base\("(?<name>(?:[^"\\]|\\.)*)", tableAlias\)""", RegexOptions.Compiled);

    private static readonly Regex BasePattern =
        new(""":\s*(?:global::SqlArtisan\.)?DbTableBase\b""", RegexOptions.Compiled);

    private static readonly Regex NamespacePattern = new(
        """^\s*namespace\s+(?<name>[^;{]+);""",
        RegexOptions.Compiled | RegexOptions.Multiline);

    // The header anywhere in the leading comments, so a license header a tool
    // prepends does not hide the file from the orphan scan.
    public static bool IsGenerated(string code) =>
        HasLeadingHeader(code) && BasePattern.IsMatch(code);

    // Compared without whitespace, which C# allows around a namespace's dots and
    // the emitter copies from --namespace: `App.Tables ` read as another namespace.
    public static bool IsInNamespace(string code, string outputNamespace) =>
        NamespacePattern.Match(code) is { Success: true } m
            && WithoutWhitespace(m.Groups["name"].Value) == WithoutWhitespace(outputNamespace);

    public static string? TableName(string code) =>
        TablePattern.Match(code) is { Success: true } m ? Unescape(m.Groups["name"].Value) : null;

    public static List<string> ColumnNames(string code) =>
        [.. ColumnPattern.Matches(code).Select(m => Unescape(m.Groups["name"].Value))];

    private static bool HasLeadingHeader(string code)
    {
        bool inBlockComment = false;

        foreach (string line in code.Split('\n'))
        {
            string trimmed = line.Trim().TrimStart('\uFEFF');

            if (inBlockComment || trimmed.StartsWith("/*", StringComparison.Ordinal))
            {
                inBlockComment = !trimmed.Contains("*/", StringComparison.Ordinal);
                continue;
            }

            if (trimmed == Header)
            {
                return true;
            }

            if (trimmed.Length > 0 && !trimmed.StartsWith("//", StringComparison.Ordinal))
            {
                return false;
            }
        }

        return false;
    }

    private static string WithoutWhitespace(string value) =>
        string.Concat(value.Where(c => !char.IsWhiteSpace(c)));

    // Reverses TableClassEmitter.Quote's escaping, so a diff names the column as it
    // reads in the database rather than as it reads inside a C# string literal.
    private static string Unescape(string literal)
    {
        StringBuilder unescaped = new(literal.Length);

        for (int i = 0; i < literal.Length; i++)
        {
            if (literal[i] != '\\')
            {
                unescaped.Append(literal[i]);
                continue;
            }

            char next = literal[++i];

            // A malformed \u — hand-edited or corrupted; Quote never emits one —
            // reads back literally rather than aborting the whole --check/--fix run.
            if (next == 'u'
                && i + 4 < literal.Length
                && int.TryParse(
                    literal.AsSpan(i + 1, 4),
                    NumberStyles.AllowHexSpecifier,
                    CultureInfo.InvariantCulture,
                    out int code))
            {
                unescaped.Append((char)code);
                i += 4;
            }
            else
            {
                unescaped.Append(next);
            }
        }

        return unescaped.ToString();
    }
}
