using System.Text;

namespace SqlArtisan.TableClassGen;

internal sealed class TableClassEmitter(CodeGenerationSettings settings)
{
    private const string Indent = "    ";

    public string Emit(CatalogTable table)
    {
        StringBuilder code = new();

        // The header marks the file as generated so a consumer's format and style
        // gates skip it; the nullable directive keeps the output compiling the same
        // way regardless of the consuming project's context.
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using SqlArtisan;");
        code.AppendLine();
        code.AppendLine($"namespace {settings.OutputNamespace};");
        code.AppendLine();
        code.AppendLine($"{settings.Accessibility} sealed class {table.ClassName} : DbTableBase");
        code.AppendLine("{");

        code.AppendLine(
            $"{Indent}public {table.ClassName}(string tableAlias = \"\") : base(\"{EmittedTableName(table)}\", tableAlias)");
        code.AppendLine($"{Indent}{{");

        foreach (CatalogColumn column in table.Columns)
        {
            code.AppendLine(
                $"{Indent}{Indent}{column.PascalCaseName} = new DbColumn(this, \"{column.Name}\");");
        }

        code.AppendLine($"{Indent}}}");

        foreach (CatalogColumn column in table.Columns)
        {
            code.AppendLine();

            if (MetadataAttribute(column) is { } attribute)
            {
                code.AppendLine($"{Indent}{attribute}");
            }

            code.AppendLine($"{Indent}public DbColumn {column.PascalCaseName} {{ get; }}");
        }

        code.AppendLine("}");

        return code.ToString();
    }

    private string EmittedTableName(CatalogTable table) =>
        settings.QualifySchema && table.Schema.Length > 0
            ? $"{table.Schema}.{table.TableName}"
            : table.TableName;

    // Only facts the catalog path determined are written: an omitted argument is the
    // unknown state, which reads as "no information" rather than "false".
    private static string? MetadataAttribute(CatalogColumn column)
    {
        List<string> arguments = [];

        if (column.IsNullable is { } isNullable)
        {
            arguments.Add($"Nullable = {Literal(isNullable)}");
        }

        if (column.HasDefault is { } hasDefault)
        {
            arguments.Add($"HasDefault = {Literal(hasDefault)}");
        }

        if (column.IsIndexed is { } isIndexed)
        {
            arguments.Add($"Indexed = {Literal(isIndexed)}");
        }

        return arguments.Count == 0
            ? null
            : $"[DbColumnMetadata({string.Join(", ", arguments)})]";
    }

    private static string Literal(bool value) => value ? "true" : "false";
}
