using System.Text;

namespace SqlArtisan.TableClassGen;

internal sealed class TableClassEmitter(CodeGenerationSettings settings)
{
    private const string Indent = "    ";

    // A property of one of these names hides a member the consumer can see, which
    // warns (CS0108) and fails a warnings-as-errors build. Gated against
    // DbTableBase's real surface by TableClassEmitterTests.
    internal static readonly HashSet<string> HidesBaseMember =
    [
        "Asterisk",
        "Equals",
        "Finalize",
        "GetHashCode",
        "GetType",
        "MemberwiseClone",
        "ReferenceEquals",
        "ToString",
    ];

    public string Emit(CatalogTable table)
    {
        GuardPropertyNames(table);

        StringBuilder code = new();

        // The header marks the file as generated so a consumer's format and style
        // gates skip it; the nullable directive keeps the output compiling the same
        // way regardless of the consuming project's context.
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using SqlArtisan;");
        code.AppendLine();
        code.AppendLine($"namespace {settings.OutputNamespace};");
        code.AppendLine();
        code.AppendLine($"{settings.Accessibility} sealed class {table.ClassName} : DbTableBase");
        code.AppendLine("{");

        code.AppendLine(
            $"{Indent}public {table.ClassName}(string tableAlias = \"\") : base({Quote(EmittedTableName(table))}, tableAlias)");
        code.AppendLine($"{Indent}{{");

        foreach (CatalogColumn column in table.Columns)
        {
            code.AppendLine(
                $"{Indent}{Indent}{column.PascalCaseName} = new DbColumn(this, {Quote(column.Name)});");
        }

        code.AppendLine($"{Indent}}}");

        foreach (CatalogColumn column in table.Columns)
        {
            code.AppendLine();

            if (MetadataAttribute(column) is { } attribute)
            {
                code.AppendLine($"{Indent}{attribute}");
            }

            string modifier = HidesBaseMember.Contains(column.PascalCaseName) ? "new " : string.Empty;

            code.AppendLine($"{Indent}public {modifier}DbColumn {column.PascalCaseName} {{ get; }}");
        }

        code.AppendLine("}");

        return code.ToString();
    }

    // Neither collision can compile, and the tool has no name-mapping option, so
    // the schema is the only place to resolve them.
    private static void GuardPropertyNames(CatalogTable table)
    {
        Dictionary<string, string> byProperty = new(StringComparer.Ordinal);

        foreach (CatalogColumn column in table.Columns)
        {
            if (column.PascalCaseName == table.ClassName)
            {
                throw new CommandLineException(
                    $"Column '{column.Name}' in table '{table.TableName}' generates the property "
                        + $"{column.PascalCaseName}, which is also the class name; rename the column.");
            }

            if (byProperty.TryGetValue(column.PascalCaseName, out string? first))
            {
                throw new CommandLineException(
                    $"Columns '{first}' and '{column.Name}' in table '{table.TableName}' both "
                        + $"generate the property {column.PascalCaseName}; rename one of them.");
            }

            byProperty[column.PascalCaseName] = column.Name;
        }
    }

    private string EmittedTableName(CatalogTable table) =>
        settings.QualifySchema && table.Schema.Length > 0
            ? $"{table.Schema}.{table.TableName}"
            : table.TableName;

    // A quoted identifier admits a quote, a backslash, and even a newline, any of
    // which would otherwise close or re-escape the C# literal it is written into.
    private static string Quote(string value)
    {
        StringBuilder quoted = new(value.Length + 2);
        quoted.Append('"');

        foreach (char c in value)
        {
            switch (c)
            {
                case '"':
                    quoted.Append("\\\"");
                    break;
                case '\\':
                    quoted.Append(@"\\");
                    break;
                default:
                    // U+2028/U+2029 end a C# source line without being control
                    // characters, so they need the escape too.
                    quoted.Append(
                        char.IsControl(c) || c is '\u2028' or '\u2029'
                            ? $"\\u{(int)c:X4}"
                            : c.ToString());
                    break;
            }
        }

        return quoted.Append('"').ToString();
    }

    // Only facts the catalog path determined are written: an omitted argument is the
    // unknown state, which reads as "no information" rather than "false".
    private static string? MetadataAttribute(CatalogColumn column)
    {
        List<string> arguments = [];

        if (column.IsNullable is { } isNullable)
        {
            arguments.Add($"Nullable = {Literal(isNullable)}");
        }

        if (column.HasDefault is { } hasDefault)
        {
            arguments.Add($"HasDefault = {Literal(hasDefault)}");
        }

        if (column.IsIndexed is { } isIndexed)
        {
            arguments.Add($"Indexed = {Literal(isIndexed)}");
        }

        // The member name, so a rename in the core follows through to the emitted
        // code instead of leaving a stale literal behind.
        if (column.TypeCategory is { } typeCategory)
        {
            arguments.Add($"TypeCategory = {nameof(DbTypeCategory)}.{typeCategory}");
        }

        return arguments.Count == 0
            ? null
            : $"[DbColumnMetadata({string.Join(", ", arguments)})]";
    }

    private static string Literal(bool value) => value ? "true" : "false";
}
