using System.Text;

namespace SqlArtisan.TableClassGen;

internal sealed class DbTableInfo(
    string tableName,
    IReadOnlyList<DbColumnInfo> columns,
    string? schema = null)
{
    private const string Indent = "    ";

    public string TableName => tableName;

    public string Schema => schema ?? string.Empty;

    public string ClassName => $"{CaseConverter.SnakeToPascalCase(tableName)}Table";

    public IReadOnlyList<DbColumnInfo> Columns => columns;

    public string GenerateCode(CodeGenerationSettings settings)
    {
        StringBuilder code = new();

        // The header marks the file as generated so a consumer's format and style
        // gates skip it; the nullable directive keeps the output compiling the same
        // way regardless of the consuming project's context.
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using SqlArtisan;");
        code.AppendLine();
        code.AppendLine($"namespace {settings.OutputNamespace};");
        code.AppendLine();
        code.AppendLine($"{settings.Accessibility} sealed class {ClassName} : DbTableBase");
        code.AppendLine("{");

        code.AppendLine(
            $"{Indent}public {ClassName}(string tableAlias = \"\") : base(\"{EmittedTableName(settings)}\", tableAlias)");
        code.AppendLine($"{Indent}{{");

        foreach (DbColumnInfo column in Columns)
        {
            code.AppendLine(
                $"{Indent}{Indent}{column.PascalCaseName} = new DbColumn(this, \"{column.Name}\");");
        }

        code.AppendLine($"{Indent}}}");

        foreach (DbColumnInfo column in Columns)
        {
            code.AppendLine();

            if (MetadataAttribute(column) is { } attribute)
            {
                code.AppendLine($"{Indent}{attribute}");
            }

            code.AppendLine($"{Indent}public DbColumn {column.PascalCaseName} {{ get; }}");
        }

        code.AppendLine("}");

        return code.ToString();
    }

    private string EmittedTableName(CodeGenerationSettings settings) =>
        settings.QualifySchema && Schema.Length > 0
            ? $"{Schema}.{TableName}"
            : TableName;

    // Only facts the catalog path determined are written: an omitted argument is the
    // unknown state, which reads as "no information" rather than "false".
    private static string? MetadataAttribute(DbColumnInfo column)
    {
        List<string> arguments = [];

        if (column.IsNullable is { } isNullable)
        {
            arguments.Add($"Nullable = {Literal(isNullable)}");
        }

        if (column.HasDefault is { } hasDefault)
        {
            arguments.Add($"HasDefault = {Literal(hasDefault)}");
        }

        if (column.IsIndexed is { } isIndexed)
        {
            arguments.Add($"Indexed = {Literal(isIndexed)}");
        }

        return arguments.Count == 0
            ? null
            : $"[DbColumnMetadata({string.Join(", ", arguments)})]";
    }

    private static string Literal(bool value) => value ? "true" : "false";
}
