using SqlArtisan.TableClassGen;

namespace SqlArtisan.TableClassGen.Tests;

public class DbTableInfoTests
{
    private static DbTableInfo Table() =>
        new(
            "user_account",
            [
                new DbColumnInfo("id", "INTEGER", isNullable: false, hasDefault: true),
                new DbColumnInfo("note", "TEXT", isNullable: true, hasDefault: false),
                new DbColumnInfo("legacy", "TEXT"),
            ],
            "app");

    [Fact]
    public void GenerateCode_KnownFacts_EmitsMetadataAttribute()
    {
        string code = Table().GenerateCode(TestSettings.Create());

        Assert.Equal(
            """
            // <auto-generated/>
            #nullable enable

            using SqlArtisan;

            namespace Generated.Tables;

            internal sealed class UserAccountTable : DbTableBase
            {
                public UserAccountTable(string tableAlias = "") : base("user_account", tableAlias)
                {
                    Id = new DbColumn(this, "id");
                    Note = new DbColumn(this, "note");
                    Legacy = new DbColumn(this, "legacy");
                }

                [DbColumnMetadata(Nullable = false, HasDefault = true)]
                public DbColumn Id { get; }

                [DbColumnMetadata(Nullable = true, HasDefault = false)]
                public DbColumn Note { get; }

                public DbColumn Legacy { get; }
            }

            """.ReplaceLineEndings(),
            code.ReplaceLineEndings());
    }

    // An undetermined fact must leave no trace: a reader of the attribute has to be
    // able to tell "not known" from "known to be false".
    [Fact]
    public void GenerateCode_UnknownFacts_EmitsNoAttribute()
    {
        DbTableInfo table = new("t", [new DbColumnInfo("c", "TEXT")]);

        Assert.DoesNotContain("DbColumnMetadata", table.GenerateCode(TestSettings.Create()));
    }

    [Fact]
    public void GenerateCode_PartiallyKnownFacts_EmitsOnlyTheDeterminedArgument()
    {
        DbTableInfo table = new(
            "t",
            [new DbColumnInfo("c", "TEXT", isNullable: true)]);

        Assert.Contains(
            "[DbColumnMetadata(Nullable = true)]",
            table.GenerateCode(TestSettings.Create()));
    }

    [Fact]
    public void GenerateCode_QualifySchema_EmitsSchemaQualifiedTableName()
    {
        string code = Table().GenerateCode(TestSettings.Create(qualifySchema: true));

        Assert.Contains("base(\"app.user_account\", tableAlias)", code);
    }

    [Fact]
    public void GenerateCode_Accessibility_EmitsTheRequestedModifier()
    {
        string code = Table().GenerateCode(TestSettings.Create(accessibility: "public"));

        Assert.Contains("public sealed class UserAccountTable : DbTableBase", code);
    }

    [Fact]
    public void GenerateCode_SameInput_IsByteIdentical()
    {
        Assert.Equal(
            Table().GenerateCode(TestSettings.Create()),
            Table().GenerateCode(TestSettings.Create()));
    }
}
