using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SqlArtisan.TableClassGen;

namespace SqlArtisan.TableClassGen.Tests;

public class TableClassEmitterTests
{
    private static CatalogTable Table() =>
        new(
            "user_account",
            [
                new CatalogColumn("id", "INTEGER", isNullable: false, hasDefault: true),
                new CatalogColumn("note", "TEXT", isNullable: true, hasDefault: false),
                new CatalogColumn("legacy", "TEXT"),
            ],
            "app");

    private static string Emit(CatalogTable table, CodeGenerationSettings? settings = null) =>
        new TableClassEmitter(settings ?? TestSettings.Create()).Emit(table);

    [Fact]
    public void Emit_KnownFacts_EmitsMetadataAttribute()
    {
        Assert.Equal(
            """
            // <auto-generated/>
            #nullable enable

            namespace Generated.Tables;

            internal sealed class UserAccountTable : global::SqlArtisan.DbTableBase
            {
                public UserAccountTable(string tableAlias = "") : base("user_account", tableAlias)
                {
                    Id = new global::SqlArtisan.DbColumn(this, "id");
                    Note = new global::SqlArtisan.DbColumn(this, "note");
                    Legacy = new global::SqlArtisan.DbColumn(this, "legacy");
                }

                [global::SqlArtisan.DbColumnMetadata(Nullable = false, HasDefault = true)]
                public global::SqlArtisan.DbColumn Id { get; }

                [global::SqlArtisan.DbColumnMetadata(Nullable = true, HasDefault = false)]
                public global::SqlArtisan.DbColumn Note { get; }

                public global::SqlArtisan.DbColumn Legacy { get; }
            }

            """.ReplaceLineEndings(),
            Emit(Table()).ReplaceLineEndings());
    }

    // An undetermined fact must leave no trace: a reader of the attribute has to be
    // able to tell "not known" from "known to be false".
    [Fact]
    public void Emit_UnknownFacts_EmitsNoAttribute()
    {
        CatalogTable table = new("t", [new CatalogColumn("c", "TEXT")]);

        Assert.DoesNotContain("DbColumnMetadata", Emit(table));
    }

    [Fact]
    public void Emit_PartiallyKnownFacts_EmitsOnlyTheDeterminedArgument()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "TEXT", isNullable: true)]);

        Assert.Contains("[global::SqlArtisan.DbColumnMetadata(Nullable = true)]", Emit(table));
    }

    [Fact]
    public void Emit_RecognizedTypeCategory_EmitsTheArgument()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "varchar", dbms: Dbms.PostgreSql)]);

        Assert.Contains(
            "[global::SqlArtisan.DbColumnMetadata("
                + "TypeCategory = global::SqlArtisan.DbTypeCategory.Text)]",
            Emit(table));
    }

    [Fact]
    public void Emit_UnrecognizedTypeCategory_OmitsTheArgument()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "geography", isNullable: true, dbms: Dbms.PostgreSql)]);

        Assert.Contains("[global::SqlArtisan.DbColumnMetadata(Nullable = true)]", Emit(table));
    }

    [Fact]
    public void Emit_QualifySchema_EmitsSchemaQualifiedTableName()
    {
        string code = Emit(Table(), TestSettings.Create(qualifySchema: true));

        Assert.Contains("base(\"app.user_account\", tableAlias)", code);
    }

    [Fact]
    public void Emit_Accessibility_EmitsTheRequestedModifier()
    {
        string code = Emit(Table(), TestSettings.Create(accessibility: "public"));

        Assert.Contains(
            "public sealed class UserAccountTable : global::SqlArtisan.DbTableBase",
            code);
    }

    [Fact]
    public void Emit_SameInput_IsByteIdentical()
    {
        Assert.Equal(Emit(Table()), Emit(Table()));
    }

    // A quoted identifier admits both on every engine, and either would end the
    // C# literal early — the shape that shipped as uncompilable output.
    [Fact]
    public void Emit_NameWithQuoteOrBackslash_EscapesTheLiteral()
    {
        CatalogTable table = new(
            "quoted",
            [new CatalogColumn("say \"hi\"", "TEXT"), new CatalogColumn("back\\slash", "TEXT")]);

        string code = Emit(table);

        Assert.Contains("""new global::SqlArtisan.DbColumn(this, "say \"hi\"")""", code);
        Assert.Contains("""new global::SqlArtisan.DbColumn(this, "back\\slash")""", code);
    }

    [Fact]
    public void Emit_TableNameWithQuote_EscapesTheLiteral() =>
        Assert.Contains(
            """base("say \"hi\"", tableAlias)""",
            Emit(new CatalogTable("say \"hi\"", [new CatalogColumn("id", "INTEGER")])));

    [Fact]
    public void Emit_NameWithControlCharacter_EscapesTheLiteral() =>
        Assert.Contains(
            """new global::SqlArtisan.DbColumn(this, "a\u000Ab")""",
            Emit(new CatalogTable("t", [new CatalogColumn("a\nb", "TEXT")])));

    // U+2028/U+2029 end a C# source line without being control characters, so
    // unescaped they break the emitted literal exactly like a newline.
    [Fact]
    public void Emit_NameWithUnicodeLineSeparator_EscapesTheLiteral()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("a\u2028b", "TEXT"), new CatalogColumn("c\u2029d", "TEXT")]);

        string code = Emit(table);

        Assert.Contains("""new global::SqlArtisan.DbColumn(this, "a\u2028b")""", code);
        Assert.Contains("""new global::SqlArtisan.DbColumn(this, "c\u2029d")""", code);
    }

    [Fact]
    public void Emit_NameHidingABaseMember_EmitsNew() =>
        Assert.Contains(
            "public new global::SqlArtisan.DbColumn Asterisk { get; }",
            Emit(new CatalogTable("t", [new CatalogColumn("asterisk", "TEXT")])));

    [Fact]
    public void Emit_OrdinaryName_EmitsNoNew() =>
        Assert.Contains("public global::SqlArtisan.DbColumn Id { get; }", Emit(Table()));

    // Reflection over the real base, so a member added to DbTableBase or
    // TableReference later cannot silently reintroduce the CS0108 it warns on.
    [Fact]
    public void HidesBaseMember_CoversEveryMemberAConsumerCanSee()
    {
        const BindingFlags All = BindingFlags.Public | BindingFlags.NonPublic
            | BindingFlags.Instance | BindingFlags.Static | BindingFlags.FlattenHierarchy;

        HashSet<string> visible =
        [
            .. typeof(DbTableBase).GetMembers(All)
                .Where(m => m switch
                {
                    MethodBase b => b.IsPublic || b.IsFamily || b.IsFamilyOrAssembly,
                    PropertyInfo p => (p.GetMethod ?? p.SetMethod) is { } a
                        && (a.IsPublic || a.IsFamily || a.IsFamilyOrAssembly),
                    FieldInfo f => f.IsPublic || f.IsFamily || f.IsFamilyOrAssembly,
                    _ => false,
                })
                .Select(m => m.Name)
                // Constructors and accessors carry no source-level name a property
                // could collide with; Finalize is the destructor, so it hides nothing.
                .Where(n => !n.StartsWith('.') && !n.StartsWith("get_") && !n.StartsWith("set_"))
                .Where(n => n != "Finalize"),
        ];

        Assert.Equal(visible.OrderBy(n => n, StringComparer.Ordinal),
            TableClassEmitter.HidesBaseMember.OrderBy(n => n, StringComparer.Ordinal));
    }

    [Fact]
    public void Emit_TwoColumnsWithOnePropertyName_ThrowsCommandLineException()
    {
        CatalogTable table = new(
            "collide",
            [new CatalogColumn("user_name", "TEXT"), new CatalogColumn("user__name", "TEXT")]);

        CommandLineException ex = Assert.Throws<CommandLineException>(() => Emit(table));

        Assert.Equal(
            "Columns 'user_name' and 'user__name' in table 'collide' both generate the property "
                + "UserName; rename one of them",
            ex.Message);
    }

    [Fact]
    public void Emit_ColumnNamedAfterTheClass_ThrowsCommandLineException()
    {
        CatalogTable table = new("user", [new CatalogColumn("user_table", "TEXT")]);

        CommandLineException ex = Assert.Throws<CommandLineException>(() => Emit(table));

        Assert.Equal(
            "Column 'user_table' in table 'user' generates the property UserTable, which is also "
                + "the class name; rename the column",
            ex.Message);
    }

    // The profile the `new` modifier protects: every base-member name, the
    // destructor name, and an all-separator name compile with warnings as errors.
    [Fact]
    public void Emit_EdgeCaseNames_CompilesWarningFree()
    {
        CatalogTable table = new(
            "edge",
            [
                new CatalogColumn("asterisk", "TEXT"),
                new CatalogColumn("equals", "TEXT"),
                new CatalogColumn("finalize", "TEXT"),
                new CatalogColumn("get_hash_code", "TEXT"),
                new CatalogColumn("get_type", "TEXT"),
                new CatalogColumn("memberwise_clone", "TEXT"),
                new CatalogColumn("reference_equals", "TEXT"),
                new CatalogColumn("to_string", "TEXT"),
                new CatalogColumn("___", "TEXT"),
            ],
            "app");

        GeneratedCodeCompiler.AssertCompiles([Emit(table)], warningsAsErrors: true);
    }

    [Fact]
    public void Emit_CombiningMarkNames_KeepsTheMarksAndCompiles()
    {
        CatalogTable table = new(
            "ลูกค้า",
            [new CatalogColumn("ชื่อ", "TEXT"), new CatalogColumn("नाम", "TEXT")]);

        string source = Emit(table);

        Assert.Contains("class ลูกค้าTable :", source);
        Assert.Contains("DbColumn ชื่อ { get; }", source);
        Assert.Contains("DbColumn नाम { get; }", source);
        GeneratedCodeCompiler.AssertCompiles([source], warningsAsErrors: true);
    }

    // C# ignores the ZWNJ when comparing names, so the guard must see one property here.
    [Fact]
    public void Emit_ColumnsDifferingByAFormattingCharacter_ThrowsCommandLineException()
    {
        CatalogTable table = new(
            "collide",
            [new CatalogColumn("ab\u200Ccd", "TEXT"), new CatalogColumn("abcd", "TEXT")]);

        CommandLineException ex = Assert.Throws<CommandLineException>(() => Emit(table));

        Assert.Equal(
            "Columns 'ab\u200Ccd' and 'abcd' in table 'collide' both generate the property "
                + "Abcd; rename one of them",
            ex.Message);
    }

    [Fact]
    public void Emit_ColumnWithNoName_ThrowsCommandLineException()
    {
        CatalogTable table = new("edge", [new CatalogColumn("", "TEXT")], "app");

        CommandLineException ex = Assert.Throws<CommandLineException>(() => Emit(table));

        Assert.Equal(
            "Column '' in table 'edge' generates no property name; rename the column",
            ex.Message);
    }

    // The file lands in the user's namespace, where each of these used to win over
    // `using SqlArtisan;`: loudly as a compile error, or silently for an attribute
    // that accepts the arguments, which turned the schema rules off.
    [Theory]
    [InlineData("namespace Generated { public class DbColumn { } }")]
    [InlineData("namespace Generated.Tables { public class DbTableBase { } }")]
    [InlineData("namespace Generated { public enum DbTypeCategory { Text } }")]
    [InlineData("global using System.Data.Common;")]
    [InlineData(
        "namespace Generated { public sealed class DbColumnMetadataAttribute : "
            + "System.Attribute { public bool Nullable { get; set; } } }")]
    public void Emit_ConsumerDeclaresACoreName_StillBindsTheCoreType(string consumer)
    {
        CatalogTable table = new(
            "user_account",
            [
                new CatalogColumn("id", "INTEGER", isNullable: false, dbms: Dbms.Sqlite),
                new CatalogColumn("db_type_category", "TEXT", dbms: Dbms.Sqlite),
            ]);

        CSharpCompilation compilation =
            GeneratedCodeCompiler.AssertCompiles([Emit(table), consumer]);

        IPropertySymbol id = (IPropertySymbol)compilation
            .GetTypeByMetadataName("Generated.Tables.UserAccountTable")!
            .GetMembers("Id")
            .Single();
        Assert.Equal("SqlArtisan.DbColumn", id.Type.ToDisplayString());
        Assert.Equal(
            "SqlArtisan.DbColumnMetadataAttribute",
            id.GetAttributes().Single().AttributeClass!.ToDisplayString());
    }

    // --lowercase reaches the table and column names only; the schema segment
    // of a qualified name keeps the case the catalog reader handed down.
    [Fact]
    public void Emit_QualifySchema_KeepsSchemaSegmentCase()
    {
        CatalogTable table = new("employees", [new CatalogColumn("id", "INTEGER")], "HR");

        string code = Emit(table, TestSettings.Create(qualifySchema: true));

        Assert.Contains("base(\"HR.employees\", tableAlias)", code);
    }
}
