using SqlArtisan.TableClassGen;

namespace SqlArtisan.TableClassGen.Tests;

public class TableClassEmitterTests
{
    private static CatalogTable Table() =>
        new(
            "user_account",
            [
                new CatalogColumn("id", "INTEGER", isNullable: false, hasDefault: true),
                new CatalogColumn("note", "TEXT", isNullable: true, hasDefault: false),
                new CatalogColumn("legacy", "TEXT"),
            ],
            "app");

    private static string Emit(CatalogTable table, CodeGenerationSettings? settings = null) =>
        new TableClassEmitter(settings ?? TestSettings.Create()).Emit(table);

    [Fact]
    public void Emit_KnownFacts_EmitsMetadataAttribute()
    {
        Assert.Equal(
            """
            // <auto-generated/>
            #nullable enable

            using SqlArtisan;

            namespace Generated.Tables;

            internal sealed class UserAccountTable : DbTableBase
            {
                public UserAccountTable(string tableAlias = "") : base("user_account", tableAlias)
                {
                    Id = new DbColumn(this, "id");
                    Note = new DbColumn(this, "note");
                    Legacy = new DbColumn(this, "legacy");
                }

                [DbColumnMetadata(Nullable = false, HasDefault = true)]
                public DbColumn Id { get; }

                [DbColumnMetadata(Nullable = true, HasDefault = false)]
                public DbColumn Note { get; }

                public DbColumn Legacy { get; }
            }

            """.ReplaceLineEndings(),
            Emit(Table()).ReplaceLineEndings());
    }

    // An undetermined fact must leave no trace: a reader of the attribute has to be
    // able to tell "not known" from "known to be false".
    [Fact]
    public void Emit_UnknownFacts_EmitsNoAttribute()
    {
        CatalogTable table = new("t", [new CatalogColumn("c", "TEXT")]);

        Assert.DoesNotContain("DbColumnMetadata", Emit(table));
    }

    [Fact]
    public void Emit_PartiallyKnownFacts_EmitsOnlyTheDeterminedArgument()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "TEXT", isNullable: true)]);

        Assert.Contains("[DbColumnMetadata(Nullable = true)]", Emit(table));
    }

    [Fact]
    public void Emit_QualifySchema_EmitsSchemaQualifiedTableName()
    {
        string code = Emit(Table(), TestSettings.Create(qualifySchema: true));

        Assert.Contains("base(\"app.user_account\", tableAlias)", code);
    }

    [Fact]
    public void Emit_Accessibility_EmitsTheRequestedModifier()
    {
        string code = Emit(Table(), TestSettings.Create(accessibility: "public"));

        Assert.Contains("public sealed class UserAccountTable : DbTableBase", code);
    }

    [Fact]
    public void Emit_SameInput_IsByteIdentical()
    {
        Assert.Equal(Emit(Table()), Emit(Table()));
    }
}
