using System.Reflection;
using SqlArtisan.TableClassGen;

namespace SqlArtisan.TableClassGen.Tests;

public class TableClassEmitterTests
{
    private static CatalogTable Table() =>
        new(
            "user_account",
            [
                new CatalogColumn("id", "INTEGER", isNullable: false, hasDefault: true),
                new CatalogColumn("note", "TEXT", isNullable: true, hasDefault: false),
                new CatalogColumn("legacy", "TEXT"),
            ],
            "app");

    private static string Emit(CatalogTable table, CodeGenerationSettings? settings = null) =>
        new TableClassEmitter(settings ?? TestSettings.Create()).Emit(table);

    [Fact]
    public void Emit_KnownFacts_EmitsMetadataAttribute()
    {
        Assert.Equal(
            """
            // <auto-generated/>
            #nullable enable

            using SqlArtisan;

            namespace Generated.Tables;

            internal sealed class UserAccountTable : DbTableBase
            {
                public UserAccountTable(string tableAlias = "") : base("user_account", tableAlias)
                {
                    Id = new DbColumn(this, "id");
                    Note = new DbColumn(this, "note");
                    Legacy = new DbColumn(this, "legacy");
                }

                [DbColumnMetadata(Nullable = false, HasDefault = true)]
                public DbColumn Id { get; }

                [DbColumnMetadata(Nullable = true, HasDefault = false)]
                public DbColumn Note { get; }

                public DbColumn Legacy { get; }
            }

            """.ReplaceLineEndings(),
            Emit(Table()).ReplaceLineEndings());
    }

    // An undetermined fact must leave no trace: a reader of the attribute has to be
    // able to tell "not known" from "known to be false".
    [Fact]
    public void Emit_UnknownFacts_EmitsNoAttribute()
    {
        CatalogTable table = new("t", [new CatalogColumn("c", "TEXT")]);

        Assert.DoesNotContain("DbColumnMetadata", Emit(table));
    }

    [Fact]
    public void Emit_PartiallyKnownFacts_EmitsOnlyTheDeterminedArgument()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "TEXT", isNullable: true)]);

        Assert.Contains("[DbColumnMetadata(Nullable = true)]", Emit(table));
    }

    [Fact]
    public void Emit_RecognizedColumnType_EmitsTheCategory()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "varchar", dbms: Dbms.PostgreSql)]);

        Assert.Contains("[DbColumnMetadata(TypeCategory = DbTypeCategory.Text)]", Emit(table));
    }

    [Fact]
    public void Emit_UnrecognizedColumnType_OmitsTheArgument()
    {
        CatalogTable table = new(
            "t",
            [new CatalogColumn("c", "geography", isNullable: true, dbms: Dbms.PostgreSql)]);

        Assert.Contains("[DbColumnMetadata(Nullable = true)]", Emit(table));
    }

    [Fact]
    public void Emit_QualifySchema_EmitsSchemaQualifiedTableName()
    {
        string code = Emit(Table(), TestSettings.Create(qualifySchema: true));

        Assert.Contains("base(\"app.user_account\", tableAlias)", code);
    }

    [Fact]
    public void Emit_Accessibility_EmitsTheRequestedModifier()
    {
        string code = Emit(Table(), TestSettings.Create(accessibility: "public"));

        Assert.Contains("public sealed class UserAccountTable : DbTableBase", code);
    }

    [Fact]
    public void Emit_SameInput_IsByteIdentical()
    {
        Assert.Equal(Emit(Table()), Emit(Table()));
    }

    // A quoted identifier admits both on every engine, and either would end the
    // C# literal early — the shape that shipped as uncompilable output.
    [Fact]
    public void Emit_NameWithQuoteOrBackslash_EscapesTheLiteral()
    {
        CatalogTable table = new(
            "quoted",
            [new CatalogColumn("say \"hi\"", "TEXT"), new CatalogColumn("back\\slash", "TEXT")]);

        string code = Emit(table);

        Assert.Contains("""new DbColumn(this, "say \"hi\"")""", code);
        Assert.Contains("""new DbColumn(this, "back\\slash")""", code);
    }

    [Fact]
    public void Emit_TableNameWithQuote_EscapesTheLiteral() =>
        Assert.Contains(
            """base("say \"hi\"", tableAlias)""",
            Emit(new CatalogTable("say \"hi\"", [new CatalogColumn("id", "INTEGER")])));

    [Fact]
    public void Emit_NameWithControlCharacter_EscapesTheLiteral() =>
        Assert.Contains(
            """new DbColumn(this, "a\u000Ab")""",
            Emit(new CatalogTable("t", [new CatalogColumn("a\nb", "TEXT")])));

    [Fact]
    public void Emit_NameHidingABaseMember_EmitsNew() =>
        Assert.Contains(
            "public new DbColumn Asterisk { get; }",
            Emit(new CatalogTable("t", [new CatalogColumn("asterisk", "TEXT")])));

    [Fact]
    public void Emit_OrdinaryName_EmitsNoNew() =>
        Assert.Contains("public DbColumn Id { get; }", Emit(Table()));

    // Reflection over the real base, so a member added to DbTableBase or
    // TableReference later cannot silently reintroduce the CS0108 it warns on.
    [Fact]
    public void HidesBaseMember_CoversEveryMemberAConsumerCanSee()
    {
        const BindingFlags All = BindingFlags.Public | BindingFlags.NonPublic
            | BindingFlags.Instance | BindingFlags.Static | BindingFlags.FlattenHierarchy;

        HashSet<string> visible =
        [
            .. typeof(DbTableBase).GetMembers(All)
                .Where(m => m switch
                {
                    MethodBase b => b.IsPublic || b.IsFamily || b.IsFamilyOrAssembly,
                    PropertyInfo p => (p.GetMethod ?? p.SetMethod) is { } a
                        && (a.IsPublic || a.IsFamily || a.IsFamilyOrAssembly),
                    FieldInfo f => f.IsPublic || f.IsFamily || f.IsFamilyOrAssembly,
                    _ => false,
                })
                .Select(m => m.Name)
                // Constructors and property accessors carry no source-level name a
                // generated property could collide with.
                .Where(n => !n.StartsWith('.') && !n.StartsWith("get_") && !n.StartsWith("set_")),
        ];

        Assert.Equal(visible.OrderBy(n => n, StringComparer.Ordinal),
            TableClassEmitter.HidesBaseMember.OrderBy(n => n, StringComparer.Ordinal));
    }

    [Fact]
    public void Emit_TwoColumnsWithOnePropertyName_ThrowsCommandLineException()
    {
        CatalogTable table = new(
            "collide",
            [new CatalogColumn("user_name", "TEXT"), new CatalogColumn("user__name", "TEXT")]);

        CommandLineException ex = Assert.Throws<CommandLineException>(() => Emit(table));

        Assert.Equal(
            "Columns 'user_name' and 'user__name' in table 'collide' both generate the property "
                + "UserName; rename one of them.",
            ex.Message);
    }

    [Fact]
    public void Emit_ColumnNamedAfterTheClass_ThrowsCommandLineException()
    {
        CatalogTable table = new("user", [new CatalogColumn("user_table", "TEXT")]);

        CommandLineException ex = Assert.Throws<CommandLineException>(() => Emit(table));

        Assert.Equal(
            "Column 'user_table' in table 'user' generates the property UserTable, which is also "
                + "the class name; rename the column.",
            ex.Message);
    }
}
