// <auto-generated />
using SqlArtisan;
using SqlArtisan.Internal;
using static SqlArtisan.Internal.ExpressionResolver;

namespace SqlArtisan.Databases.Sqlite;

public static partial class Sql
{
    public static SqliteQuery Select(params object[] selectItems) =>
        new((ISqlBuilder)global::SqlArtisan.Sql.Select(selectItems));

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.Sqlite);

    public static CeilFunction Ceil(object expr) =>
        new(Resolve(expr), Dbms.Sqlite);

    public static CeilingFunction Ceiling(object expr) =>
        new(Resolve(expr), Dbms.Sqlite);
}

public sealed class SqliteQuery
{
    private readonly ISqlBuilder _inner;

    internal SqliteQuery(ISqlBuilder inner) => _inner = inner;

    public SqlStatement Build() => _inner.Build(Dbms.Sqlite);
}
