// <auto-generated />
using SqlArtisan;
using SqlArtisan.Internal;
using static SqlArtisan.Internal.ExpressionResolver;

namespace SqlArtisan.Databases.Oracle;

public static class Sql
{
    public static OracleQuery Select(params object[] selectItems) =>
        new((ISqlBuilder)global::SqlArtisan.Sql.Select(selectItems));

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.Oracle);

    public static CeilFunction Ceil(object expr) =>
        new(Resolve(expr), Dbms.Oracle);
}

public sealed class OracleQuery
{
    private readonly ISqlBuilder _inner;

    internal OracleQuery(ISqlBuilder inner) => _inner = inner;

    public SqlStatement Build() => _inner.Build(Dbms.Oracle);
}
