// <auto-generated />
using SqlArtisan;
using SqlArtisan.Internal;
using static SqlArtisan.Internal.ExpressionResolver;

namespace SqlArtisan.Databases.PostgreSql;

public static partial class Sql
{
    public static PostgreSqlQuery Select(params object[] selectItems) =>
        new((ISqlBuilder)global::SqlArtisan.Sql.Select(selectItems));

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.PostgreSql);

    public static CeilFunction Ceil(object expr) =>
        new(Resolve(expr), Dbms.PostgreSql);

    public static CeilingFunction Ceiling(object expr) =>
        new(Resolve(expr), Dbms.PostgreSql);
}

public sealed class PostgreSqlQuery
{
    private readonly ISqlBuilder _inner;

    internal PostgreSqlQuery(ISqlBuilder inner) => _inner = inner;

    public SqlStatement Build() => _inner.Build(Dbms.PostgreSql);
}
