// <auto-generated />
using SqlArtisan;
using SqlArtisan.Internal;
using static SqlArtisan.Internal.ExpressionResolver;

namespace SqlArtisan.Databases.SqlServer;

public static class Sql
{
    public static SqlServerQuery Select(params object[] selectItems) =>
        new((ISqlBuilder)global::SqlArtisan.Sql.Select(selectItems));

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.SqlServer);

    public static CeilingFunction Ceiling(object expr) =>
        new(Resolve(expr), Dbms.SqlServer);
}

public sealed class SqlServerQuery
{
    private readonly ISqlBuilder _inner;

    internal SqlServerQuery(ISqlBuilder inner) => _inner = inner;

    public SqlStatement Build() => _inner.Build(Dbms.SqlServer);
}
