// <auto-generated />
using SqlArtisan;
using SqlArtisan.Internal;
using static SqlArtisan.Internal.ExpressionResolver;

namespace SqlArtisan.Databases.MySql;

public static class Sql
{
    public static MySqlQuery Select(params object[] selectItems) =>
        new((ISqlBuilder)global::SqlArtisan.Sql.Select(selectItems));

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.MySql);

    public static CeilFunction Ceil(object expr) =>
        new(Resolve(expr), Dbms.MySql);

    public static CeilingFunction Ceiling(object expr) =>
        new(Resolve(expr), Dbms.MySql);
}

public sealed class MySqlQuery
{
    private readonly ISqlBuilder _inner;

    internal MySqlQuery(ISqlBuilder inner) => _inner = inner;

    public SqlStatement Build() => _inner.Build(Dbms.MySql);
}
