using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SqlArtisan.Generator;

// Emits one `SqlArtisan.Databases.<Dbms>.Sql` facade per DBMS from a single
// tab-separated catalog (`*.catalog.tsv`, supplied as an AdditionalFile). Each
// facade exposes only the functions whose catalog row lists that DBMS — the
// universal rows are emitted identically into every facade at zero marginal
// maintenance cost. This is the mechanism that makes per-DBMS namespaces
// tractable (the duplication the hand-written approach could never sustain).
[Generator]
public sealed class PerDbmsFacadeGenerator : IIncrementalGenerator
{
    private static readonly string[] AllDbms =
    {
        "MySql", "Oracle", "PostgreSql", "Sqlite", "SqlServer",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<FunctionSpec>> specs =
            context.AdditionalTextsProvider
                .Where(static file =>
                    file.Path.EndsWith(".catalog.tsv", StringComparison.OrdinalIgnoreCase))
                .Select(static (file, ct) => file.GetText(ct)?.ToString() ?? string.Empty)
                .SelectMany(static (text, _) => ParseCatalog(text))
                .Collect();

        context.RegisterSourceOutput(specs, static (productionContext, functions) =>
        {
            foreach (string dbms in AllDbms)
            {
                string source = EmitFacade(dbms, functions);
                productionContext.AddSource(
                    $"SqlArtisan.Databases.{dbms}.g.cs",
                    SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private sealed class FunctionSpec
    {
        public FunctionSpec(string name, string nodeType, ImmutableArray<string> supportedDbms)
        {
            Name = name;
            NodeType = nodeType;
            SupportedDbms = supportedDbms;
        }

        public string Name { get; }

        public string NodeType { get; }

        public ImmutableArray<string> SupportedDbms { get; }
    }

    private static IEnumerable<FunctionSpec> ParseCatalog(string text)
    {
        foreach (string rawLine in text.Split('\n'))
        {
            string line = rawLine.Trim();
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            string[] columns = line.Split('\t');
            if (columns.Length < 3)
            {
                continue;
            }

            ImmutableArray<string> dbms = columns[2]
                .Split(',')
                .Select(static token => token.Trim())
                .Where(static token => token.Length > 0)
                .ToImmutableArray();

            yield return new FunctionSpec(columns[0].Trim(), columns[1].Trim(), dbms);
        }
    }

    private static string EmitFacade(string dbms, ImmutableArray<FunctionSpec> functions)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using SqlArtisan;");
        sb.AppendLine("using SqlArtisan.Internal;");
        sb.AppendLine("using static SqlArtisan.Internal.ExpressionResolver;");
        sb.AppendLine();
        sb.AppendLine($"namespace SqlArtisan.Databases.{dbms};");
        sb.AppendLine();
        sb.AppendLine("public static class Sql");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {dbms}Query Select(params object[] selectItems) =>");
        sb.AppendLine("        new((ISqlBuilder)global::SqlArtisan.Sql.Select(selectItems));");

        foreach (FunctionSpec function in functions
            .Where(f => f.SupportedDbms.Contains(dbms))
            .OrderBy(f => f.Name, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"    public static {function.NodeType} {function.Name}(object expr) =>");
            sb.AppendLine($"        new(Resolve(expr), Dbms.{dbms});");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {dbms}Query");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ISqlBuilder _inner;");
        sb.AppendLine();
        sb.AppendLine($"    internal {dbms}Query(ISqlBuilder inner) => _inner = inner;");
        sb.AppendLine();
        sb.AppendLine($"    public SqlStatement Build() => _inner.Build(Dbms.{dbms});");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
