// <auto-generated /> (image of the generated SQL Server facade)
//
// What a user writes:   using SqlArtisan.Proof.SqlServer;
// What IntelliSense offers under `Sql.`:  Abs, Ceiling, Select  — and NOT Ceil.
// Same catalog as Oracle, different surface.

using SqlArtisan.Proof;
using static SqlArtisan.Proof.ExpressionResolver;

namespace SqlArtisan.Proof.SqlServer;

public static class Sql
{
    public static SelectBuilder Select(SqlExpression projection) =>
        new(projection, Dbms.SqlServer);

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.SqlServer);

    /// <summary>The <c>CEILING(expr)</c> function. (SQL Server has no <c>CEIL</c>.)</summary>
    public static CeilingFunction Ceiling(object expr) =>
        new(Resolve(expr), Dbms.SqlServer);

    // No Ceil() here — absent by design, so it can never be typed on SQL Server.
}
