// <auto-generated /> (image of the generated Oracle facade)
//
// What a user writes:   using SqlArtisan.Proof.Oracle;
// What IntelliSense offers under `Sql.`:  Abs, Ceil, Select  — and NOT Ceiling.
// Every node is stamped Dbms.Oracle; Select binds the build target to Oracle, so
// Build() needs no Dbms argument.

using SqlArtisan.Proof;
using static SqlArtisan.Proof.ExpressionResolver;

namespace SqlArtisan.Proof.Oracle;

public static class Sql
{
    public static SelectBuilder Select(SqlExpression projection) =>
        new(projection, Dbms.Oracle);

    public static AbsFunction Abs(object expr) =>
        new(Resolve(expr), Dbms.Oracle);

    /// <summary>The <c>CEIL(expr)</c> function. (Oracle has no <c>CEILING</c>.)</summary>
    public static CeilFunction Ceil(object expr) =>
        new(Resolve(expr), Dbms.Oracle);

    // No Ceiling() here — absent by design, so it can never be typed on Oracle.
}
